In [1]:
import tensorflow as tf

import pandas as pd

In [2]:
df = pd.read_csv('train.csv')
df = df.drop(['Name', 'PassengerId'], axis=1)
df

Survived  Pclass     Sex   Age  SibSp  Parch            Ticket     Fare  \
0           0       3    male  22.0      1      0         A/5 21171   7.2500   
1           1       1  female  38.0      1      0          PC 17599  71.2833   
2           1       3  female  26.0      0      0  STON/O2. 3101282   7.9250   
3           1       1  female  35.0      1      0            113803  53.1000   
4           0       3    male  35.0      0      0            373450   8.0500   
..        ...     ...     ...   ...    ...    ...               ...      ...   
886         0       2    male  27.0      0      0            211536  13.0000   
887         1       1  female  19.0      0      0            112053  30.0000   
888         0       3  female   NaN      1      2        W./C. 6607  23.4500   
889         1       1    male  26.0      0      0            111369  30.0000   
890         0       3    male  32.0      0      0            370376   7.7500   

    Cabin Embarked  
0     NaN        S  
1     C85        C  
2     NaN        S  
3    C123        S  
4     NaN        S  
..    ...      ...  
886   NaN        S  
887   B42        S  
888   NaN        S  
889  C148        C  
890   NaN        Q  

[891 rows x 10 columns]

In [3]:
x_train = df.iloc[:, 1:].values
y_train = df.iloc[:, 0].values
x_train

array([[3, 'male', 22.0, ..., 7.25, nan, 'S'],
       [1, 'female', 38.0, ..., 71.2833, 'C85', 'C'],
       [3, 'female', 26.0, ..., 7.925, nan, 'S'],
       ...,
       [3, 'female', nan, ..., 23.45, nan, 'S'],
       [1, 'male', 26.0, ..., 30.0, 'C148', 'C'],
       [3, 'male', 32.0, ..., 7.75, nan, 'Q']], dtype=object)

In [5]:
from sklearn.preprocessing import LabelEncoder
toNum = LabelEncoder()
x_train[:, 1] = toNum.fit_transform(x_train[:, 1])
x_train[:, 5] = toNum.fit_transform(x_train[:, 5])
x_train[:, 7] = toNum.fit_transform(x_train[:, 7])
x_train[:, 8] = toNum.fit_transform(x_train[:, 8])
x_train

array([[3, 1, 22.0, ..., 7.25, 147, 2],
       [1, 0, 38.0, ..., 71.2833, 81, 0],
       [3, 0, 26.0, ..., 7.925, 147, 2],
       ...,
       [3, 0, nan, ..., 23.45, 147, 2],
       [1, 1, 26.0, ..., 30.0, 60, 0],
       [3, 1, 32.0, ..., 7.75, 147, 1]], dtype=object)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
import numpy as np
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x_train[:, 2:3])
x_train[:, 2:3] = imputer.transform(x_train[:, 2:3])
x_train

array([[ 0.82737724,  0.73769513, -0.5924806 , ..., -0.50244517,
         0.45150219,  0.58111394],
       [-1.56610693, -1.35557354,  0.63878901, ...,  0.78684529,
        -1.38162664, -1.93846038],
       [ 0.82737724, -1.35557354, -0.2846632 , ..., -0.48885426,
         0.45150219,  0.58111394],
       ...,
       [ 0.82737724, -1.35557354,  0.        , ..., -0.17626324,
         0.45150219,  0.58111394],
       [-1.56610693,  0.73769513, -0.2846632 , ..., -0.04438104,
        -1.9648949 , -1.93846038],
       [ 0.82737724,  0.73769513,  0.17706291, ..., -0.49237783,
         0.45150219, -0.67867322]])

In [9]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100, criterion='entropy', random_state=0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [10]:
y_pred = classifier.predict(x_train)

In [11]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_train, y_pred))

0.9988776655443322


In [14]:
test = pd.read_csv('test.csv')
passengerId = test.iloc[:, 0].values
test = test.drop(['Name', 'PassengerId'], axis=1)
x_test = test.iloc[:,:].values

In [15]:
from sklearn.preprocessing import LabelEncoder
toNum = LabelEncoder()
x_test[:, 1] = toNum.fit_transform(x_test[:, 1])
x_test[:, 5] = toNum.fit_transform(x_test[:, 5])
x_test[:, 7] = toNum.fit_transform(x_test[:, 7])
x_test[:, 8] = toNum.fit_transform(x_test[:, 8])
x_test

array([[3, 1, 34.5, ..., 7.8292, 76, 1],
       [3, 0, 47.0, ..., 7.0, 76, 2],
       [2, 1, 62.0, ..., 9.6875, 76, 1],
       ...,
       [3, 1, 38.5, ..., 7.25, 76, 2],
       [3, 1, nan, ..., 8.05, 76, 2],
       [3, 1, nan, ..., 22.3583, 76, 0]], dtype=object)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_test = sc.fit_transform(x_test)

import numpy as np
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x_test[:, 2:3])
x_test[:, 2:3] = imputer.transform(x_test[:, 2:3])
x_test[:, 2:3] = imputer.transform(x_test[:, 7:8])

x_test
x_test = np.nan_to_num(x_test)

In [20]:
y_test_pred = classifier.predict(x_test)
len(x_test)


418

In [21]:
data = {
    'PassengerId': passengerId,
    'Survived': y_test_pred
}
df = pd.DataFrame(data)
submission = 'submission.csv'
df.to_csv(submission, index=False)
print("new file created:", submission)
len(x_test)

new file created: submission.csv


418